### ISSUE TITLE
ansible-container build fails with AttributeError: 'tuple' object has no attribute 'id'

### ISSUE THREAD

**Issue by jas02** [ansible/ansible-container#884]
##### ISSUE TYPE

 - Bug Report
 

##### container.yml 

```
version: "2"
settings:
  conductor:
    base: centos:7
  project_name: venv
services: {}
registries: {}
```

##### OS / ENVIRONMENT

```
Ansible Container, version 0.9.2
Darwin, Lumirs-MacBook-Pro.local, 17.4.0, Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64, x86_64
3.5.2 (default, Oct 11 2016, 05:05:28)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] /Users/username/Tests/Tieto/ManageIQ_CloudForms/tmp4/venv/bin/python3.5
{
  "Driver": "aufs",
  "KernelVersion": "4.9.60-linuxkit-aufs",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "NFd": 22,
  "RegistryConfig": {
    "Mirrors": [],
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Mirrors": [],
        "Secure": true,
        "Official": true,
        "Name": "docker.io"
      }
    },
    "AllowNondistributableArtifactsCIDRs": [],
    "AllowNondistributableArtifactsHostnames": []
  },
  "ContainersStopped": 9,
  "Isolation": "",
  "OperatingSystem": "Docker for Mac",
  "Containers": 9,
  "Debug": true,
  "DriverStatus": [
    [
      "Root Dir",
      "/var/lib/docker/aufs"
    ],
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Dirs",
      "155"
    ],
    [
      "Dirperm1 Supported",
      "true"
    ]
  ],
  "CPUSet": true,
  "SystemStatus": null,
  "MemTotal": 5190017024,
  "SystemTime": "2018-02-13T10:24:09.35633282Z",
  "CgroupDriver": "cgroupfs",
  "SwapLimit": true,
  "MemoryLimit": true,
  "Labels": [],
  "IPv4Forwarding": true,
  "DefaultRuntime": "runc",
  "LiveRestoreEnabled": false,
  "SecurityOptions": [
    "name=seccomp,profile=default"
  ],
  "GenericResources": null,
  "ID": "PXXV:5WIR:HZMZ:HQYJ:WU6S:UR63:WLRF:WBTH:X5FJ:FGQE:SOOL:I3AQ",
  "ClusterStore": "",
  "InitBinary": "docker-init",
  "Name": "linuxkit-025000000001",
  "HttpProxy": "docker.for.mac.http.internal:3128",
  "NEventsListener": 2,
  "OomKillDisable": true,
  "NGoroutines": 41,
  "DockerRootDir": "/var/lib/docker",
  "ServerVersion": "17.12.0-ce",
  "ContainerdCommit": {
    "Expected": "89623f28b87a6004d4b785663257362d1658a729",
    "ID": "89623f28b87a6004d4b785663257362d1658a729"
  },
  "Images": 87,
  "ExperimentalBuild": true,
  "Runtimes": {
    "runc": {
      "path": "docker-runc"
    }
  },
  "OSType": "linux",
  "KernelMemory": true,
  "NCPU": 2,
  "InitCommit": {
    "Expected": "949e6fa",
    "ID": "949e6fa"
  },
  "LoggingDriver": "json-file",
  "CPUShares": true,
  "Plugins": {
    "Authorization": null,
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "logentries",
      "splunk",
      "syslog"
    ],
    "Volume": [
      "local"
    ]
  },
  "BridgeNfIp6tables": true,
  "ClusterAdvertise": "",
  "NoProxy": "",
  "Architecture": "x86_64",
  "ContainersPaused": 0,
  "BridgeNfIptables": true,
  "HttpsProxy": "docker.for.mac.http.internal:3129",
  "CpuCfsPeriod": true,
  "ContainersRunning": 0,
  "CpuCfsQuota": true,
  "RuncCommit": {
    "Expected": "b2567b37d7b75eb4cf325b77297b140ea686ce8f",
    "ID": "b2567b37d7b75eb4cf325b77297b140ea686ce8f"
  },
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "RemoteManagers": null,
    "ControlAvailable": false,
    "Error": ""
  }
}
{
  "Version": "17.12.0-ce",
  "KernelVersion": "4.9.60-linuxkit-aufs",
  "Experimental": true,
  "BuildTime": "2017-12-27T20:12:29.000000000+00:00",
  "ApiVersion": "1.35",
  "GitCommit": "c97c6d6",
  "Os": "linux",
  "Components": [
    {
      "Version": "17.12.0-ce",
      "Details": {
        "GitCommit": "c97c6d6",
        "Arch": "amd64",
        "Os": "linux",
        "KernelVersion": "4.9.60-linuxkit-aufs",
        "Experimental": "true",
        "MinAPIVersion": "1.12",
        "BuildTime": "2017-12-27T20:12:29.000000000+00:00",
        "ApiVersion": "1.35",
        "GoVersion": "go1.9.2"
      },
      "Name": "Engine"
    }
  ],
  "Platform": {
    "Name": ""
  },
  "Arch": "amd64",
  "MinAPIVersion": "1.12",
  "GoVersion": "go1.9.2"
}
```
##### SUMMARY

(Probably) since I installed k8s extension to ansible-container (pip install ansible-container==0.9.2[docker,k8s]) I am unable to build containers using ansible container.

During ansible-container build I am receiving error:

```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
ERROR	Unknown exception
Traceback (most recent call last):
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/docker/engine.py", line 1070, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'

```

When I run the command **ansible-container --debug build**, it works as expected. It look like there is problem getting tarball_file.

##### STEPS TO REPRODUCE

```
virtualenv --python=python3.5 --no-site-packages venv
cd venv/
source bin/activate .
pip install ansible-container[docker]
ansible-container build
```

##### EXPECTED RESULTS

Running build

##### ACTUAL RESULTS

```
Building Docker Engine context...
Starting Docker build of Ansible Container Conductor image (please be patient)...
ERROR	Unknown exception
Traceback (most recent call last):
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/Users/username/Tests/ManageIQ_CloudForms/tmp4/venv/lib/python3.5/site-packages/container/docker/engine.py", line 1070, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'
```

**Comment by hipponix** [comment]
try this command :

 pip install docker==2.7.0

**Comment by permanentdaylight** [comment]
I recently ran into this myself. As @mircosantori mentioned above, I think the current way around this is to install a version of docker < 3.0

**Comment by zentavr** [comment]
I have the same problem on my Mac and the trick with `pip install -U docker==2.7.0` worked.

**Comment by jas02** [comment]
It works, many thanks!

**Comment by j00bar** [comment]
This was fixed in #870.

**Comment by djfang** [comment]
@j00bar I'm still seeing the error in 0.93r0 without the `--debug` flag.

```
conductor_id=245084b7895e1167adfd506c44dc20350f250a161020568670101814af4bd159 save_container=False
$ ansible-container --var-file vars.yml build
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/home/dev/git-repo/ansible-container/container/cli.py", line 302, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/dev/git-repo/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/dev/git-repo/ansible-container/container/core.py", line 184, in hostcmd_build
    environment=env_vars
  File "/home/dev/git-repo/ansible-container/container/docker/engine.py", line 107, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/home/dev/git-repo/ansible-container/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/dev/git-repo/ansible-container/container/docker/engine.py", line 1156, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'
```

`ansible-container --var-file vars.yml --debug build` works though.

**Comment by maludwig** [comment]
This also worked for me, I'm also on a Mac. For future people though, you may want to see if there is a more recent version of docker 2. This is easy enough:
```
$ pip install docker==
Collecting docker==
  Could not find a version that satisfies the requirement docker== (from versions: 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.7.0, 3.0.0, 3.0.1, 3.1.0, 3.1.1)
No matching distribution found for docker==
```
As of this writing, docker==2.7.0 is the latest

**Comment by eaglet3d** [comment]
Installing docker 2.7.0 did not fix it for me when following the hello-word ansible-container instructions.  However, adding the --debug option does build as expected.
* Using vitualenv
* Ansible Container, version 0.9.2
* pip install docker==2.7.0 ... installed.
* ansible-container build
```
Building Docker Engine context...	
Starting Docker build of Ansible Container Conductor image (please be patient)...	
ERROR	Unknown exception	
Traceback (most recent call last):
  File "/home/ralph/.local/lib/python3.6/site-packages/container/cli.py", line 299, in __call__
    getattr(core, u'hostcmd_{}'.format(args.subcommand))(**vars(args))
  File "/home/ralph/.local/lib/python3.6/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ralph/.local/lib/python3.6/site-packages/container/core.py", line 181, in hostcmd_build
    environment=env_vars
  File "/home/ralph/.local/lib/python3.6/site-packages/container/docker/engine.py", line 105, in __wrapped__
    return fn(self, *args, **kwargs)
  File "/home/ralph/.local/lib/python3.6/site-packages/container/__init__.py", line 28, in __wrapped__
    return fn(*args, **kwargs)
  File "/home/ralph/.local/lib/python3.6/site-packages/container/docker/engine.py", line 1070, in build_conductor_image
    return image.id
AttributeError: 'tuple' object has no attribute 'id'
```

**Comment by kc-cloud** [comment]
Yes, adding the --debug option made it work

**Comment by soroushatarod** [comment]
I did set the docker  to 2.7.0 but I'm getting ordereddict is not JSON serializable. Did anyone faced this issue?

**Comment by tzok** [comment]
@soroushatarod and others who find this by keywords `ordereddict` or `JSON not serializable`. This is a separate issue and you can find more in #958 and bugfix PR #959

**Comment by Voronenko** [comment]
@tzok If you see duplicates, please comment them to link the original issue. Thanks a lot!
